import PushNotifications from './PushNotifications';
import PushNotificationsList from './PushNotificationsList';
import PushNotificationsListItem from './PushNotificationsListItem';
import APNSPushNotificationsListItem from './APNS/APNSPushNotificationsListItem';
import APNSPushNotificationsActions from './APNS/APNSPushNotificationsActions';
import APNSPushNotificationsStore from './APNS/APNSPushNotificationsStore';
import APNSConfigDialog from './APNS/APNSConfigDialog';
import APNSDialogStore from './APNS/APNSConfigDialogStore';
import GCMPushNotificationsListItem from './GCM/GCMPushNotificationsListItem';
import GCMPushNotificationsActions from './GCM/GCMPushNotificationsActions';
import GCMPushNotificationsStore from './GCM/GCMPushNotificationsStore';
import GCMConfigDialog from './GCM/GCMConfigDialog';
import GCMDialogStore from './GCM/GCMConfigDialogStore';
import APNSPushNotificationsSummaryDialog from './APNS/APNSPushNotificationsSummaryDialog';
import GCMSummaryDialog from './GCM/GCMSummaryDialog';

PushNotifications.List = PushNotificationsList;
PushNotifications.ListItem = PushNotificationsListItem;
PushNotifications.APNSListItem = APNSPushNotificationsListItem;
PushNotifications.APNSActions = APNSPushNotificationsActions;
PushNotifications.APNSStore = APNSPushNotificationsStore;
PushNotifications.APNSConfigDialog = APNSConfigDialog;
PushNotifications.APNSDialogStore = APNSDialogStore;
PushNotifications.GCMListItem = GCMPushNotificationsListItem;
PushNotifications.GCMActions = GCMPushNotificationsActions;
PushNotifications.GCMStore = GCMPushNotificationsStore;
PushNotifications.GCMConfigDialog = GCMConfigDialog;
PushNotifications.GCMDialogStore = GCMDialogStore;
PushNotifications.SummaryDialog = APNSPushNotificationsSummaryDialog;
PushNotifications.GCMSummaryDialog = GCMSummaryDialog;

export default PushNotifications;
