/* Component tests generated by react-snapshot-test-generator on 2016-10-31T13:01:33.920Z */

import React from 'React'
import renderer from 'react-test-renderer'

function snapshotTest(element) {
  const tree = renderer.create(element).toJSON()
  console.log(tree)
  expect(tree).toMatchSnapshot()
}



import CloseButton from '../src/common/CloseButton'


describe('<CloseButton />', () => {
  it('renders correctly', () => {
    snapshotTest(<CloseButton />)
  })
})
